### ISSUE TITLE
Electron client

### ISSUE THREAD

**Issue by notramo** [CTemplar/webclient#562] opened 2020-04-03 19:46 UTC
It would be good to have an Electron client. Users could then build it directly from source, check that one once, and use that checked build several times. If they have an encrypted computer, even the session could persist between app restart.
Probably this is the most important feature for the webapp - easily verify the source code **once**, and reuse it.

**Comment by Godfry** [comment] 2020-04-07 08:43
@notramo Some of our very best ideas have been from community contributors like you, so thank you for this suggestion that could improve my service.  I don't understand code, so before I add it to the development schedule I'll need to have my team look into it first to make certain it can fit with our service.  If it checks out we'll add it to the schedule.  I post updated schedules to Reddit every so often.  I've made a note to check back with you about updates to this suggestion but please forgive me if I forget.  
Kind Regards to you:)

**Comment by techevanglist** [comment] 2020-04-09 09:52
duplicate of https://github.com/CTemplar/webclient/issues/405

**Comment by techevanglist** [comment] 2020-04-09 10:05
@notramo  We are going to add a very basic version of Electron client for CTemplar

**Comment by techevanglist** [comment] 2020-04-10 13:06
https://github.com/CTemplar/webclient/releases/tag/v2.3.0

**Closed by techevanglist** 2020-04-10 13:06 UTC
