### ISSUE TITLE
Enable tab navigation on composer form

### ISSUE THREAD

**Issue by FP1996** [CTemplar/webclient#1288] opened 2021-06-23 09:41 UTC
### Your environment

Firefox

### Steps to reproduce

Start a new mail. I use the full-screen composer in case that makes a difference.
Click on the 'Subject' and type a word or two.
Press "Tab" to go to the main text area.

### Expected behavior

A single tab makes cursor land in the main text area and I can start typing my email.

### Actual behavior

Pressing tab in the 'subject' field seems to move my cursor somewhere between the subject and the main text area. I have to use the mouse to move to the main text area.

**Comment by superdev0714** [comment] 2021-07-07 08:17
I tried to reproduce this issue, but it works on my end as expected.

**Comment by The-Hidden-Hand** [comment] 2021-07-07 12:35
@FP1996 
I'm also unable to reproduce with Firefox 78.11.0esr on Linux. It works with the normal and full-screen composer window.

Perhaps a short demo would be helpful, and make sure it's not because of any addon, I'm not sure how else we can debug.

My demo:

https://user-images.githubusercontent.com/45569116/124759852-a5964100-df1f-11eb-837d-a91787b69faf.mp4

**Comment by FP1996** [comment] 2021-07-08 20:37
Thanks for the details.

It looks like the bug requires your signature to be empty. So you need to go to the settings, "Signatures & Aliases" tab and remove the text you have in the signature area. So it has the placeholder text instead.

Please let me know if that helps you reproduce the problem.

**Comment by superdev0714** [comment] 2021-07-09 09:19
@FP1996 @The-Hidden-Hand 
It is still works fine on my end.

https://user-images.githubusercontent.com/33947302/125055383-81507680-e07d-11eb-98a1-ce376813af50.mp4

**Comment by FP1996** [comment] 2021-07-09 10:26
you asked for a demo, maybe that helps clear things up.

I use Firefox built by Archlinux, 89.0.2
No extentions at all. Its started in its own profile (firefox -P email)

sorry for the kruler as a crude way to hide details.

https://user-images.githubusercontent.com/86202601/125064143-9e526d00-e0b0-11eb-8bc2-ed295e60b219.mp4

I guess I could have pressed tab slower, now there is only half a second between the first press of tab and the second one. But you can clearly see the cursor not be there for a bit if you know what to look for.

**Comment by The-Hidden-Hand** [comment] 2021-08-09 12:18
It works on Firefox Linux for me. I'm closing until getting more reports because we are unable to reproduce by ourselves.

**Closed by The-Hidden-Hand** 2021-08-09 12:18 UTC
Labels: enhancement, priority
