### ISSUE TITLE
Use our own icons set (+ four related UI issues)

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/webclient#939] opened 2021-01-15 18:48 UTC
- [x] Dates should be always in a single line
![image](https://user-images.githubusercontent.com/45569116/107381701-080d2180-6ae7-11eb-82e5-3b59501bab19.png)

- [x] Forwarded arrow is not vertically aligned
![image](https://user-images.githubusercontent.com/45569116/109717666-46ee3e80-7b9e-11eb-901e-3b28392beec7.png)

- [x] The shield cuts the text. This happened after a change because originally, the shield goes at the end of the title.

![image](https://user-images.githubusercontent.com/45569116/111969552-476d5b80-8af2-11eb-91e4-b36437608abb.png)

Original: 

![image](https://user-images.githubusercontent.com/45569116/111969602-5522e100-8af2-11eb-9a1b-6d96b90b47f8.png)

---
---

- [x] **Use icons from the UI KIT located in Zeplin.io, these are few examples:**

![image](https://user-images.githubusercontent.com/45569116/104763484-de6a1000-575d-11eb-8073-d78a3071a175.png)

![image](https://user-images.githubusercontent.com/45569116/104763507-e924a500-575d-11eb-8aec-e0598d0e3cdb.png)

![image](https://user-images.githubusercontent.com/45569116/104763731-41f43d80-575e-11eb-814b-16a2b6f075a2.png)

![image](https://user-images.githubusercontent.com/45569116/104763884-7bc54400-575e-11eb-870a-518842da1a89.png)

![image](https://user-images.githubusercontent.com/45569116/104765007-1e31f700-5760-11eb-90ec-1f8ebadae256.png)

---
---

- [x] **The actions bar looks uneven:**

![image](https://user-images.githubusercontent.com/45569116/104764335-289fc100-575f-11eb-8b64-a5d143661c07.png)

**Comment by happyman125** [comment] 2021-01-26 03:55
@The-Hidden-Hand I have some questions.
1. Use icons from the UI KIT located in Zeplin.io, these are few examples:
 Now we are using fontawesome icons. So you want to use assets in zeplin design? If we need to use them, we will download and add those assets from zeplin to our project to use. are you okay with that?
2.  Align tabs and their wording as per the design:
 you mean to follow design to align tabs? Now design is old design so many things are changed. If we change tabs, we will need to change some contents included in them.

**Comment by happyman125** [comment] 2021-01-28 15:23
Two items are left. 
1. change icon to design assets. still in progress and will take much time
2. The actions bar looks uneven: I am not sure why it looks uneven. could you clarify?

**Comment by The-Hidden-Hand** [comment] 2021-01-29 19:59
> The actions bar looks uneven: I am not sure why it looks uneven. Could you clarify?

@happyman125 
At least the checkbox square isn't vertically aligned in the container.

**Comment by happyman125** [comment] 2021-01-29 20:03
@The-Hidden-Hand Yes, checkbox should be in center. and I already requested asset for last icon so it will be fixed when we replace design asset.

**Comment by The-Hidden-Hand** [comment] 2021-02-28 10:37
@happyman125 
I added one point at the beginning to review dates. They must be in a single line always.

**Comment by The-Hidden-Hand** [comment] 2021-03-22 13:27
@happyman125 
When do you think we can have all the new icons working, aligned, and well detailed?

I've added some side effects caused by recent changes too, please review them altogether.

**Comment by happyman125** [comment] 2021-03-22 15:07
@The-Hidden-Hand if you are okay with designer's new font icons, I think we need to replace all of current assets.

**Comment by The-Hidden-Hand** [comment] 2021-03-22 15:16
@happyman125 
Yes, I think they are fine, and in any case, the designer can update them at any time as long as the website is ready for using them. It would be just updating the font or the image files. (I would prefer font if it's reliable, but not sure you and the team)

**Comment by happyman125** [comment] 2021-03-22 15:22
@The-Hidden-Hand The updating of website can be started after all assets are prepared using font.
Also, I am not sure about font because we mostly use same font images on website so if design builds svg with same height and width, we can use it without any change.
Anyway, I think we need to replace all of current assets first.

**Comment by The-Hidden-Hand** [comment] 2021-03-22 15:28
@happyman125 
I thought you already started and only have remaining the pending assets from the designer.

**Comment by happyman125** [comment] 2021-03-22 15:33
@The-Hidden-Hand I think you want to implement font icons as she provided? If yes, we need to have all same style assets. Origin assets don't have font style like new icons.
Also, we should consider light/dark theme change about icons so this is big task.

**Comment by The-Hidden-Hand** [comment] 2021-03-22 15:59
@happyman125 
We need you to solve assignments by making the best decisions, no matter how big or small the task is. You have a few options, PNG (+ retina), SVG, or Font Glyph, and a designer working for this. The only requirement is to complete the task by getting a good-looking and well performant solution.

I'm not sure about changing all the icons without making any structural change, especially in those cases the icons are misaligned or with the wrong size. We also have to solve those details within this task. Please, bring some certainty.

Are you able to do it? Do you need anything else from the team or me? When do you estimate it can be completed?

**Comment by happyman125** [comment] 2021-03-22 16:06
@The-Hidden-Hand yeah, I understand what you mean. Sure, My tasks should be completed by me with the best solution.
Of course, I will fix issues of this task and I only mentioned about our icons change plan. (just mentioned as big task)

I meant some of this task are related with implementation of new icons.
Ok, As you suggested, I will fix current issues of this task first.
We can consider new icons later maybe.

**Comment by happyman125** [comment] 2021-03-22 19:28
I can't reproduce second issue.
 Replied arrow is not vertical aligned

**Comment by The-Hidden-Hand** [comment] 2021-03-22 20:43
It happens after I reply to any external email (eg: from prod to dev).

**Comment by The-Hidden-Hand** [comment] 2021-03-23 08:16
@happyman125 
It doesn't happen when reply, it happens when forwarding a message.
I misread the icon!

**Comment by happyman125** [comment] 2021-03-23 17:21
@The-Hidden-Hand I can't reproduce it when forward. it looks good on my side.
Also, I think we need to decide about design assets. so what is your final decision about new icons?

**Comment by The-Hidden-Hand** [comment] 2021-03-23 17:30
@happyman125 
Which one do you think is better for our situation?

**Comment by The-Hidden-Hand** [comment] 2021-03-23 17:36
> I can't reproduce it when forward. it looks good on my side.

It happens to me in production and development every single time :thinking: 
I'm using Firefox.

**Comment by happyman125** [comment] 2021-03-23 17:40
IMO, I think it is good if we use any icons packs like font awesome. Now we are using mostly font awesome icons and also implemented light/dark themes based on that. 
If we use any other images(not icons), we will need new approach to implement light/dark theme.

Also, I will check on firefox.

**Comment by The-Hidden-Hand** [comment] 2021-03-23 23:06
> IMO, I think it is good if we use any icons packs like font awesome. Now we are using mostly font awesome icons and also implemented light/dark themes based on that.
> If we use any other images(not icons), we will need new approach to implement light/dark theme.
> 
> Also, I will check on firefox.

@superdev0714
I would like a third opinion about the icons.
Did you see the original design on Zeplin? Do you think it is worth the effort/reward?

**Comment by superdev0714** [comment] 2021-03-24 10:46
@The-Hidden-Hand 
I checked design on Zeplin before, we have gap for the original design.
Regarding Icon, I don't think it's good to update as SVG, we need to use font, if insist to use zeplin's icon, we can change it to font by ourselves.
What I am suggesting now is as following.
1. Create the font from the SVG that should be replaced with on Zeplin 
 - We can use icomoon for this.
 - Define our own fonts pack rules such as naming family...
2. Create the fonts pack naming our own on the project
 - Currently we have several fonts on the project and don't need to remove them.
 - Create our own fonts pack, for example ctemplarfonts, which All of new or updated fonts should be placed here

**Closed** 2021-03-26 17:07 UTC
Labels: enhancement
