### ISSUE TITLE
Corrupted text

### ISSUE THREAD

**Issue by argxentakato** [CTemplar/webclient#1725] opened 2022-04-07 09:07 UTC
![image](https://user-images.githubusercontent.com/14871483/162162330-ee676b8a-a973-4730-b58d-ce7f9e329fb0.png)

### Your environment

OS: Arch Linux
Kernel: Linux 5.15.32 (LTS)
Web browser: Firefox 98.0.2

### Picture, video or steps to reproduce

1. ~~Live in Japan~~
2. Receive emails in which ISO-2022-JP format text encoding is used.

### Explanation

I reported this issue on Reddit 6 months ago and was told on Reddit that I should report it on GitHub, so I am creating an issue. Maybe you already know...

I cannot be sure, but CTemplar probably cannot interpret non-UTF-8 formatted emails correctly.

**Comment by OneWhiteBird** [comment] 2022-04-14 20:25
Possible duplicate of https://github.com/CTemplar/backend/issues/2127

**Closed** 2022-04-19 15:01 UTC
Labels: bug
