### ISSUE TITLE
Improve page loading time

### ISSUE THREAD

**Issue by zenithium** [CTemplar/webclient#519] opened 2020-03-05 21:16 UTC
**Is your feature request related to a problem? Please describe.**
It is frustrating to see 3s-10s loading animation for every page visited on the site.

**Describe the solution you'd like**
Switching to static web pages

**Describe alternatives you've considered**
Prioritizing static content to load and showing that first while the rest is loading

**Comment by Godfry** [comment] 2020-03-09 19:10
Hello @zenithium We're working on this item and we'll have it improved in the future.  
Part of the problem is it takes time to move through all the layers of security.  That being said I am sure we can improve this.  Thank you for the suggestion

**Comment by zenithium** [comment] 2020-03-10 13:43
I am glad to already see big improvements on this issue

**Comment by atifsaddique211f** [comment] 2020-03-10 14:08
@zenithium We have removed the loader, I hope that solve the problem of loading on each page.
I'm going to close this issue, if you still face the issue, please feel free to reopen.

**Closed by atifsaddique211f** 2020-03-10 14:08 UTC
